personal_site_ror/config/routes.rb
Rails.application.routes.draw do
  get 'todos/index'

  get 'welcome/index'
  get 'todos/done'
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
  resources :journals
  resources :articles do
      resources :comments
  end
  resources :users
  resources :welcome
  resources :todos
end

personal_site_ror/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

personal_site_ror/app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                  length: { minimum: 5 }
end

personal_site_ror/app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

personal_site_ror/app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

personal_site_ror/app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

personal_site_ror/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

personal_site_ror/app/models/journal.rb
class Journal < ApplicationRecord
end

personal_site_ror/app/models/todo.rb
class Todo < ApplicationRecord
end

personal_site_ror/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

personal_site_ror/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:edit, :update, :show, :delete]
  def index
    @articles  = Article.all
  end
  def new
    @article = Article.new
  end


  def create

      @article = Article.new(article_params)
      if @article.save
        redirect_to article_path(@article)
      else
        render 'new'
      end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
  private
  def article_params
    params.require(:article).permit(:title, :text)
  end

  def find_article
    @article = Article.find(params[:id])
  end

end

personal_site_ror/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
   @article = Article.find(params[:article_id])
   @comment = @article.comments.find(params[:id])
   @comment.destroy
   redirect_to article_path(@article)
 end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

personal_site_ror/app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :delete]

  #index action to render all posts
  def index
    @posts = Journal.all
  end

  #new action for creating post

  def new
    @post = Journal.new
  end

  #create action saves the new post into database
  def create
    @post = Journal.new(post_params)

    if @post.save
      flash[:notice] = "Successfully created post"
      redirect_to journal_path(@post)
    else
      flash[:alert] = "Error creating new post!"
      render :new
    end

  end

  #edit action retrieves the post and renders the edit page

  def edit
  end

  #update action update the post with new info

  def update
    if @post.update_attributes(post_params)
      flash[:notice] = "Succesfully updated post!"
      redirect_to journal_path(@post)
    else
      flash[:alert] = "Error updating post!"
      render :edit
    end
  end

  #The show action renders the individual post after retrieving the id
  def show
  end

  def destroy
    @post = Journal.find(params[:id])
    if @post.destroy
      flash[:notice] = "succesfully deleted post!"
      redirect_to journals_path
    else
      flash[:alert] = "Error updating the post!"
    end
  end



  private
  def post_params
    params.require(:journal).permit(:title, :body)
  end

  def find_post
    @post = Journal.find(params[:id])
  end
end

personal_site_ror/app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :find_todo, only: [:edit, :update, :show, :delete]
    def index
      @todos = Todo.all
      #@articles  = Article.all
    end
    def new
      #@article = Article.new
      @todo = Todo.new
    end


    def create
        @todo = Todo.new(todo_params)
        @todo.done = 0
        if @todo.save
          redirect_to todos_path
        else
          render 'new'
        end
    end

    def show
      #@article = Article.find(params[:id])
    end

    def edit
      #@article = Article.find(params[:id])
    end

    def update
      if @todo.update(todo_params)
        redirect_to todos_path
      else
        render 'edit'
      end
    end

    def destroy
      #@article = Article.find(params[:id])
      #@article.destroy
      #redirect_to articles_path
      @todo = Todo.find(params[:id])
      @todo.destroy
      redirect_to todos_path
    end


    def done
      @todo = Todo.find(params[:id])
      @todo.update_attribute(:done, 1)
      redirect_to todos_path
      end
    private

    def todo_params
      params.require(:todo).permit(:title, :category, :done)
    end


    def find_todo
      @todo = Todo.find(params[:id])
    end

end

personal_site_ror/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.saves
      log_in @user
      flash[:success] = "Welcome to nikmay's site"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


end

personal_site_ror/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

personal_site_ror/app/helpers/application_helper.rb
module ApplicationHelper
end

personal_site_ror/app/helpers/articles_helper.rb
module ArticlesHelper
end

personal_site_ror/app/helpers/comments_helper.rb
module CommentsHelper
end

personal_site_ror/app/helpers/journals_helper.rb
module JournalsHelper
end

personal_site_ror/app/helpers/todos_helper.rb
module TodosHelper
end

personal_site_ror/app/helpers/users_helper.rb
module UsersHelper
end

personal_site_ror/app/helpers/welcome_helper.rb
module WelcomeHelper
end

personal_site_ror/app/views/articles/_form.html.erb
<%= simple_form_for @article do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

personal_site_ror/app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'All articles', articles_path %>

personal_site_ror/app/views/articles/index.html.erb
<%= link_to 'New article', new_article_path %>

<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %> </td>
      <td><%= link_to 'Delete' ,article_path(article) , method: :delete, data: {confirm: 'Are you sure?'} %> </td>
    </tr>
  <% end %>
</table>

personal_site_ror/app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'All articles', articles_path %>

personal_site_ror/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'All articles', articles_path %>

personal_site_ror/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

personal_site_ror/app/views/comments/_form.html.erb
<%= simple_form_for [@article, @article.comments.build]  do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

personal_site_ror/app/views/comments/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Add a comment:</h2>
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

personal_site_ror/app/views/journals/_form.html.erb
<%= simple_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>ew

personal_site_ror/app/views/journals/edit.html.erb
<h2>Edit Post</h2>

<%= render "journals/form" %>

<%= link_to 'All articles', journals_path %>

personal_site_ror/app/views/journals/index.html.erb
<% stylesheet_link_tag "journals.scss" %>

<div class="container-fluid">
  <div class="row content">
    <div class="col-xs-3">

      <ul class="nav" data-spy="affix" data-offset-top="1">
        </br>
        </br>
        </br>
        <li> <h4>Journals</h4> </li>
        <li> <%= link_to 'New entry', new_journal_path %></li>
        <li> <%= link_to 'Home', controller: 'welcome' %></li>
      </ul><br>
    </div>
      <div class="col-xs-9">
      <% @posts.each do |post| %>
          <h2><%= link_to post.title , journal_path(post) %></h2>
          <h6><%= post.created_at.strftime('%b %d, %Y') %></h6>
          <p><%= raw(post.body).truncate(128) %></p>
          <p><%= raw(post.body).split.size %> Words. </p>
        </br>
        <%= link_to "Edit", controller: "journals", action: "edit", id: post.id %>
        <%= link_to "Delete", journal_path(post),  method: :delete, data: {confirm: "Are you sure?"}  %>
        <hr>
        <%end%>
      </div>





    </div>


  </div>

personal_site_ror/app/views/journals/new.html.erb
<h2>Create New Post</h2>

<%= render "journals/form" %>

<%= link_to 'All entries', journals_path %>

personal_site_ror/app/views/journals/show.html.erb
<div class="col-sm-11 col-xs-12 blog-content">
  <h2 class="text-center"><%= @post.title %></h2>
  <h5 class="text-center"><%= @post.created_at.strftime('%b %d, %Y') %></h5>
  <div><%= raw @post.body %></div>
</div>
<%= link_to 'Edit', edit_journal_path(@post) %>
<%= link_to 'All journals', journals_path %>

personal_site_ror/app/views/todos/_done_todos.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <strong><th>Urgent</th></strong>
      <strong><th>Not Urgent</th></strong>
    </tr>
  </thead>
  <tbody>
    <tr>
      <strong><th>important</th></strong>
      <td>
         <% @todos.each do |todo| %>
          <% if todo.category == 1 and todo.done == true %>
          <%= link_to todo.title, edit_todo_path(todo) %>(
          <%= link_to 'Delete ' ,todo_path(todo) , method: :delete, data: {confirm: 'Are you sure?'} %>)
          </br>
          <%end%>
          <%end%>
      </td>
      <td>
        <% @todos.each do |todo| %>
         <% if todo.category == 2 and todo.done == true %>
         <%= link_to todo.title, edit_todo_path(todo) %> (<%= link_to 'Delete ' ,todo_path(todo) , method: :delete, data: {confirm: 'Are you sure?'} %>)
         </br>
         <%end%>
         <%end%>

      </td>
    </tr>
    <tr>
      <strong><th>Not important</th></strong>
      <td>
        <% @todos.each do |todo| %>
         <% if todo.category == 3 and todo.done == true %>
         </br>
         <%= link_to todo.title, edit_todo_path(todo) %> (<%= link_to 'Delete ' ,todo_path(todo) , method: :delete, data: {confirm: 'Are you sure?'} %>)
         <%end%>
         <%end%>
      </td>
      <td>
        <% @todos.each do |todo| %>
         <% if todo.category == 4 and todo.done == true %>
         <%= link_to todo.title, edit_todo_path(todo) %>(<%= link_to 'Delete ' ,todo_path(todo) , method: :delete, data: {confirm: 'Are you sure?'} %>)
         </br>
         <%end%>
         <%end%>
      </td>
    </tr>
  </tbody>
</table>

</table>

personal_site_ror/app/views/todos/_form.html.erb
<%= simple_form_for @todo do |form| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@todo.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @todo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :category %><br>
    <%= form.select :category, [['Urgent and Important', 1], ['Not urgent and Important' , 2], ['Urgent and Not Important', 3], ['Not urgent and not Important', 4]] %>
  </p>


  <p>
    <%= form.submit %>
  </p>

<% end %>

personal_site_ror/app/views/todos/_todos.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <strong><th>Urgent</th></strong>
      <strong><th>Not Urgent</th></strong>
    </tr>
  </thead>
  <tbody>
    <tr>
      <strong><th>important</th></strong>
      <td>
         <% @todos.each do |todo| %>
          <% if todo.category == 1 and todo.done == false %>
          <%= link_to todo.title, edit_todo_path(todo) %>(
          <%= link_to 'done', controller: 'todos', action: 'done' , id: todo.id%>
          <%= link_to 'Delete ' ,todo_path(todo) , method: :delete, data: {confirm: 'Are you sure?'} %>)
          </br>
          <%end%>
          <%end%>
      </td>
      <td>
        <% @todos.each do |todo| %>
         <% if todo.category == 2 and todo.done == false %>
         <%= link_to todo.title, edit_todo_path(todo) %> (<%= link_to 'done', controller: 'todos', action: 'done' , id: todo.id%>
<%= link_to 'Delete ' ,todo_path(todo) , method: :delete, data: {confirm: 'Are you sure?'} %>)
         </br>
         <%end%>
         <%end%>

      </td>
    </tr>
    <tr>
      <strong><th>Not important</th></strong>
      <td>
        <% @todos.each do |todo| %>
         <% if todo.category == 3 and todo.done == false %>
         </br>
         <%= link_to todo.title, edit_todo_path(todo) %> (<%= link_to 'done', controller: 'todos', action: 'done' , id: todo.id%>
<%= link_to 'Delete ' ,todo_path(todo) , method: :delete, data: {confirm: 'Are you sure?'} %>)
         <%end%>
         <%end%>
      </td>
      <td>
        <% @todos.each do |todo| %>
         <% if todo.category == 4 and todo.done == false %>
         <%= link_to todo.title, edit_todo_path(todo) %>(<%= link_to 'done', controller: 'todos', action: 'done' , id: todo.id%>
<%= link_to 'Delete ' ,todo_path(todo) , method: :delete, data: {confirm: 'Are you sure?'} %>)
         </br>
         <%end%>
         <%end%>
      </td>
    </tr>
  </tbody>
</table>

</table>

personal_site_ror/app/views/todos/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

personal_site_ror/app/views/todos/index.html.erb
<h1>TODO's</h1>
<%= link_to 'New todo', new_todo_path %>
<h1> Done todos </h1>
<%= render 'todos' %>
<h1> Not done todos </h1>
<%= render 'done_todos' %>

personal_site_ror/app/views/todos/new.html.erb
<h1>Add todo</h1>

<%= render 'form' %>

personal_site_ror/app/views/todos/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @todo.category %>
</p>

<p>
  <strong>Done:</strong>
  <%= @todo.done %>
</p>

personal_site_ror/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

personal_site_ror/app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

personal_site_ror/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

personal_site_ror/app/views/welcome/index.html.erb
<h1>Welcome to Nikmay</h1>